project_id = "vjdzzaerrxfctkkiwkmn"

[functions.send-loan-application]
verify_jwt = false

[functions.scrape-autoplius]
verify_jwt = true

[functions.add-watermark]
verify_jwt = true

[functions.send-car-purchase]
verify_jwt = false

[functions.generate-autoplius-xml]
verify_jwt = true

[functions.submit-inquiry]
verify_jwt = false

[functions.submit-car-search]
verify_jwt = false
